version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379

  mongo:
    image: tutum/mongodb
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
      - "28017:28017"
    environment:
      - AUTH=NO